version: "2"
services:
  db:
    image: mysql:5.6
    restart: always
    env_file: db-env.dev
    volumes:
      - ./instances/db/conf/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./instances/db/conf/my.cnf:/etc/mysql/my.cnf
      - ./instances/db/logs:/var/log/
      - ./instances/db/data:/var/lib/mysql
      - ./instances/db/sql/:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
  web:
    build: ./instances/web/
    restart: always
    env_file: web-env.dev
    volumes:
      - ./instances/web/public/:/var/www/public
    links:
      - php
      - db
  php:
    build: ./instances/php/
    restart: always
    volumes:
      - ./instances/web/public:/var/www/public
    ports:
      - "9000"
